fix(*): Make test can use top level await alfy file.
SamVerschueren/alfy-test pull request #9
Opened 2020-10-09 07:36 UTC by duncup

This package not support top level await before, but alfy support.

2020-10-19 03:27 UTC, duncup commented
@sindresorhus @SamVerschueren

2020-10-19 23:55 UTC, sindresorhus commented
Can you explain your changes? Why are you now bundling the `run-node` script?

2020-10-20 11:11 UTC, SamVerschueren commented
I don't see why these changes would make it support top level await all of a sudden? It has to do with the underlying Node version that's being used I assume?

Unless Alfred is using one of these environment variables https://github.com/sindresorhus/run-node/commit/9a69ce77e8995f53b3ba21fb8b8369e1550fa974, I don't see how these changes would actually make it work?

2020-10-21 07:39 UTC, duncup commented
Alfy have support top level await.
https://github.com/sindresorhus/alfy/pull/109
IF i use it, alfy-test has been not work.
And i never see the code in run-node, just copy from the case use in alfy. 

@SamVerschueren 

----------

There always run it, and isee the pr for alfy how add top level await, and got this script, so i copy it. because i don't think change the run-node is a good idea.
@sindresorhus

2020-10-27 07:48 UTC, duncup commented
Anything?

2020-10-28 15:08 UTC, SamVerschueren commented
So the thing here is that `alfy-test` uses a different `run-node` than `alfy`. It appears that `alfy` has a custom `run-node` script that enables `ESM` right [here](https://github.com/sindresorhus/alfy/pull/109/files#diff-b4d5381c19220196a4f924339b9e5beaf8588e23b2d3c2c0d2320d1436a762e2R46).

@sindresorhus would it make sense to create a new `alfy-run-node` package or something that can be used by `alfy-test` as well? I guess that would allow us to support ESM here as well.

2020-10-28 22:03 UTC, sindresorhus commented
I would just copy-paste it here for now. Node.js will eventually support top-level await by default. We can open an issue to revert back to `run-node` at such time.

2020-12-17 04:10 UTC, duncup commented
Anything?

2021-02-20 02:00 UTC, duncup commented
Did this project alive?

2021-02-20 06:33 UTC, SamVerschueren commented
Sorry, totally missed that you updated your PR. I'll com back to you later today.

2021-02-20 09:38 UTC, duncup commented
I know that you guys too busy, so don't be sorry.
But i really need fix this.

Anyway, thank you for you guys make this.

2021-02-21 09:01 UTC, SamVerschueren requested changes
One small comment.

2021-02-21 09:01 UTC, SamVerschueren commented on package.json
> +	  "ava": "ava"
```suggestion
	  "test": "xo && ava"
```

2021-05-27 06:28 UTC, SamVerschueren requested changes

2021-05-27 06:28 UTC, SamVerschueren commented on package.json
> +	  "test": "xo && ava"
```suggestion
		"test": "xo && ava"
```

2021-05-27 06:29 UTC, merged

2021-12-09 21:52 UTC, rchl commented
This change is a bit controversial to me.

When having both `alfy` and `alfy-test` installed, the `alfy-test`'s `.bin/run-node` takes over the one included by `alfy` and breaks things because it tries to use `esm` which I haven't installed.

The `run-node` from `alfy` just runs plain node and it works with top level await if the package has `module` type and using node 14+.

So if I want to run in plain node without esm then this change breaks things for me. I have to either install `esm` or only install the production dependencies.

2021-12-10 07:47 UTC, SamVerschueren commented
We might want to keep this in line with the `run-node.sh` from Alfy. https://github.com/sindresorhus/alfy/blob/main/run-node.sh

Alfy moved to ESM entirely in August and thus got rid of the `esm` flag provided to Node. I think we want to align both of them. PR welcome.

2021-12-10 22:09 UTC, rchl commented
I guess that would entitle switching this package to be an ES module itself? So a breaking change.